export enum DriveType {
    GASOLINE_ENGINE = 'GASOLINE_ENGINE',
    DIESEL_ENGINE = 'DIESEL_ENGINE',
    ELECTRICITY_230V = 'ELECTRICITY_230V',
    ELECTRICITY_400V = 'ELECTRICITY_400V',
    POWERED_BY_VEHICLE = 'POWERED_BY_VEHICLE'
}