export enum EquipmentType {
    TECHNICAL_EQUIPMENT = 'TECHNICAL_EQUIPMENT',
    MEDICAL_EQUIPMENT = 'MEDICAL_EQUIPMENT',
    FIRE_EXTINGUISHING_EQUIPMENT = 'FIRE_EXTINGUISHING_EQUIPMENT',
    OTHER_EQUIPMENT = 'OTHER_EQUIPMENT'
}